lWeekdays <- c('Monday',
               'Tuesday',
               'Wednesday',
               'Thursday',
               'Friday',
               'Saturday',
               'Sunday')

lCommitteeShortNames <- c(
  "Budget",
  "Health",
  "Foreign affairs",
  "Legal affairs",
  "Environment",
  "Internal affairs",
  "Finance",
  "Urban development",
  "Economic affairs",
  "Rules of procedure",
  "Social affairs",
  "International development",
  "Agriculture",
  "Transport"
)

names(lCommitteeShortNames) <- c(
  "Haushaltsausschuss",
  "Ausschuss für Gesundheit",
  "Auswärtiger Ausschuss",
  "Ausschuss für Recht und Verbraucherschutz",
  "Ausschuss für Umwelt, Naturschutz und nukleare Sicherheit",
  "Ausschuss für Inneres und Heimat",
  "Finanzausschuss",
  "Ausschuss für Bau, Wohnen, Stadtentwicklung und Kommunen",
  "Ausschuss für Wirtschaft und Energie",
  "Ausschuss für Wahlprüfung, Immunität und Geschäftsordnung",
  "Ausschuss für Arbeit und Soziales",
  "Ausschuss für wirtschaftliche Zusammenarbeit und Entwicklung",
  "Ausschuss für Ernährung und Landwirtschaft",
  "Ausschuss für Verkehr und digitale Infrastruktur"
)

lTopicsShortNames <- c(
  'Health',
  'Legal affairs',
  'Foreign affairs',
  'Defence',
  'Social policy',
  'Administrative affairs',
  'Agriculture',
  'Science & Technology',
  'Parliamentary affairs',
  'Environment',
  'Internal Security',
  'Labour and Employment',
  'Energy',
  'Public Finances',
  'European Policy',
  'Regional affairs',
  'Economy',
  'Budget',
  'Lobbyism & Transparency',
  'Political life, parties',
  'International trade',
  'Media / IT',
  'Financial affairs',
  'International development',
  'Immigration',
  'Humanitarian Aid',
  'Human Rights',
  'Home Affairs',
  'Social Security',
  'Nature Conservation',
  'Transport',
  'Family',
  'New Federal States',
  'Regional affairs',
  'Education',
  'Gender equality',
  'Digital agenda',
  'Senior citizens',
  'Rules of Procedure',
  'Cultural affairs'
)
names(lTopicsShortNames) <- c(
  'Gesundheit',
  'Recht',
  'Außenpolitik und internationale Beziehungen',
  'Verteidigung',
  'Gesellschaftspolitik, soziale Gruppen',
  'Staat und Verwaltung',
  'Landwirtschaft und Ernährung',
  'Wissenschaft, Forschung und Technologie',
  'Parlamentsangelegenheiten',
  'Umwelt',
  'Innere Sicherheit',
  'Arbeit und Beschäftigung',
  'Energie',
  'Öffentliche Finanzen, Steuern und Abgaben',
  'Europapolitik und Europäische Union',
  'Raumordnung, Bau- und Wohnungswesen',
  'Wirtschaft',
  'Haushalt',
  'Lobbyismus & Transparenz',
  'Politisches Leben, Parteien',
  'Außenwirtschaft',
  'Medien, Kommunikation und Informationstechnik',
  'Finanzen',
  'Entwicklungspolitik',
  'Ausländerpolitik, Zuwanderung',
  'Humanitäre Hilfe',
  'Menschenrechte',
  'Innere Angelegenheiten',
  'Soziale Sicherung',
  'Naturschutz',
  'Verkehr',
  'Familie',
  'Neue Bundesländer',
  'Regionales',
  'Bildung und Erziehung',
  'Frauen',
  'Digitale Agenda',
  'Senioren',
  'Geschäftsordnung',
  'Kultur'
)
